version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./config_rabbitMq/definitions.json:/opt/definitions.json:ro
      - ./config_rabbitMq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  redis:
    image: redis:6.2.4-alpine
    container_name: redis
    ports:
      - "6379:6379"